### ISSUE TITLE
E2 - Importación de un fichero con un diseño no funciona en otro curso #10095

### ISSUE THREAD

**Issue by jumarub** [uniadaptiveLTI/uniadaptiveLTI-Front#20]
E2 - Importación de un fichero con un diseño
Cuando se hace sobre un mismo curso, funciona correctamente.
Cuando se hace sobre otro curso:
* No importa las precondiciones y relaciones entre los bloques
* Los bloques llegan vacíos, pero no se muestra gráficamente con la exclamación. Tampoco el módulo de validación indica que están vacíos.
* El nombre del elemento antiguo se mantiene, pero debería indicar de alguna forma que es el elemento del que proviene.

**Comment by jumarub** [comment]
The conditions are not imported because it belongs to another course, and the elements are not identical.

We are currently working on the validation module, and it is not functioning as expected when importing the design file.

**Comment by rafaugr** [comment]
Las condiciones deben ser exportadas para que la exportación en ficheros del mapa tenga sentido

**Comment by Javiondox** [comment]
Currently,

The exported JSON files contain the contents of a course map.

If this is imported into the same course, it is assumed that all resources exist. Therefore, it is imported with the same conditions and resources.

If it is exported to another course, the resources do not have to be the same, so it is assumed that the same resources will not be reused, so the blocks are set to empty (but keeping the original name). Since the resources do not exist, maintaining the conditions may not make sense. So these are removed.

**Comment by rafaugr** [comment]
Como se especifica en el pliego, se puede hacer un diseño en la herramienta que contenga bloques abstractos (no asignados a un recurso) indicando precondiciones y relaciones con otros bloques. Luego para que sea un mapa válido y exportable al LMS todos los elementos del mapa tendrán que tener un recurso asociado.

**Comment by Javiondox** [comment]
Should be fixed right now. Reopen if needed.

**Comment by rafaugr** [comment]
![image](https://github.com/uniadaptiveLTI/uniadaptiveLTI-Front/assets/125374554/df0f3c1d-8934-401b-b900-c3670d8cb9ee)

Cuando se intenta crear una relación tras un mapa importado a través del fichero, aparece ese error.
Insistimos en que las relaciones importadas deberían aparecer.
Reopen please.

**Comment by jumarub** [comment]
The error occurs because when blocks are imported from another course, they lose their relationships, conditions, and completion constraints. We are working on preserving these features.
