### ISSUE TITLE
Bloque no aparece tras importación desde el LMS

### ISSUE THREAD

**Issue by rafaugr** [uniadaptiveLTI/uniadaptiveLTI-Front#97]
Pasos para reproducir:
1. Última versión del código
2. En moodle tenemos una tarea que tiene como restricción de acceso una condición de calificación de un Examen. Si no se cumple dicha restricción el elemento se oculta.
3. En la herramienta: Importar desde moodle
El bloque que tiene la restricción mencionada, no se importa y no aparece en el mapa.

Se puede aplicar a cualquier elemento. (Tarea, examen...)

**Comment by BAOOBAP** [comment]
We have been testing with importing resources with qualifying conditions, and it imports these resources without problems, we recommend updating the project with a git pull to bring in the fixes.

**Comment by rafaugr** [comment]
La condición da igual, lo único en común con los bloques que no se importan es que tienen una condición que si no se cumple está oculta. Puede tener que ver con los permisos del usuario del webservice?

**Comment by BAOOBAP** [comment]
mmm, it may be because of the user permissions, have you added the permissions listed by the service, just in case, I attach the list of permissions required for it:

moodle/course:update: Update course settings

moodle/course:viewhiddencourses: View hidden courses

moodle/course:changecategory: Change the category of the course

moodle/course:changefullname: Change the full course name

moodle/course:changeshortname: Change the short name of the course

moodle/course:changeidnumber: Change the ID number of the course

moodle/course:changesummary: Change the course summary

moodle/course:visibility: Hide/show courses

moodle/user:viewdetails: View user profiles

moodle/user:viewhiddendetails: View hidden details of users

moodle/course:useremail: Enable/disable email addresses

moodle/user:update: Update user profiles moodle/site:accessallgroups: Update user profiles

moodle/site:accessallgroups: Access all groups

moodle/course:viewparticipants: View participants

moodle/course:managegroups: Manage groups

gradereport/user:view: View user report moodle/course:user:view: View user report

**Comment by rafaugr** [comment]
Hemos conseguido solucionarlo, el arquetipo ideal para el usuario del webservice es Profesor con permisos de edición. En concreto, para que no ocurra lo descrito en esta tarea, se debe tener la capacidad: course:ignoreavailabilityrestrictions
Por favor, tenedlo en cuenta para la documentación final.
